lint:
  files_exist:
    - .github/workflows/awstest.yml
    - .github/workflows/branch.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-bifrost_logo_light.png
    - docs/images/nf-core-bifrost_logo_light.png
    - docs/images/nf-core-bifrost_logo_dark.png
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  included_configs: false
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - custom_config
    - params.custom_config_version
    - params.custom_config_base
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Joe Reynolds, Mark Liddell, Jonathan Manning
  description: Bifrost pipeline
  force: false
  is_nfcore: false
  name: bifrost
  org: seqera-services
  outdir: .
  skip_features:
    - igenomes
    - nf_core_configs
    - multiqc
    - fastqc
    - email
    - adaptivecard
    - slackreport
  version: 1.0.0dev
