lint:
  actions_awstest: false
  actions_awsfulltest: false
  files_exist:
    - .github/workflows/awstest.yml
    - .github/workflows/branch.yml
    - CODE_OF_CONDUCT.md
    - assets/email_template.html
    - assets/email_template.txt
    - assets/multiqc_config.yml
    - assets/nf-core-bifrost_logo_light.png
    - assets/sendmail_template.txt
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - docs/images/nf-core-bifrost_logo_dark.png
    - docs/images/nf-core-bifrost_logo_light.png
  files_unchanged:
    - assets/sendmail_template.txt
  included_configs: false
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - custom_config
    - params.custom_config_version
    - params.custom_config_base
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  nf_test_content:
    - tests/default.nf.test
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Joe Reynolds, Mark Liddell, Jonathan Manning
  description: Bifrost pipeline
  force: false
  is_nfcore: false
  name: bifrost
  org: seqera-services
  outdir: .
  skip_features:
    - igenomes
    - nf_core_configs
    - multiqc
    - fastqc
    - email
    - adaptivecard
    - slackreport
  version: 1.0.0dev
