channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.12
  - conda-forge::cmdstanpy=1.2.4
  - conda-forge::numpy=2.1.0
  - conda-forge::pandas=2.2.2
  - conda-forge::scipy=1.14.1
  - conda-forge::pyyaml=6.0.1
